ingest/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('list_jobs', views.list_jobs, name='list_jobs'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('synaptogram.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'openid/', include('djangooidc.urls')),
    url('ingest/', include('ingest.urls')),
]

synaptogram/urls.py
from django.conf.urls import url

from . import views

app_name = 'synaptogram'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^coll_list$', views.coll_list, name='coll_list'),
    url(r'^exp_list/(?P<coll>[-\w]+)/$', views.exp_list, name='exp_list'),
    url(r'^cutout/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/$',
        views.cutout, name='cutout'),
    url(r'^sgram/$', views.sgram, name='sgram'),
    url(r'^ndviz_url/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/(?P<channel>[-\w]+)/$',
        views.get_ndviz_url, name='ndviz_url'),
    url(r'^ndviz_url/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/$',
        views.get_ndviz_url, {'channel': None}, name='ndviz_url'),
    url(r'^ndviz_url_list/$', views.ndviz_url_list, name='ndviz_url_list'),
    url(r'^tiff_stack/$', views.tiff_stack, name='tiff_stack'),
    url(r'^tiff_stack_channel/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/(?P<x>[-\w:]+)/(?P<y>[-\w:]+)/(?P<z>[-\w:]+)/(?P<channel>[-\w:]+)/(?P<res>[-\w:]+)/$',
        views.tiff_stack_channel, name='tiff_stack_channel'),
    url(r'^zip_tiff_stacks/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/(?P<x>[-\w:]+)/(?P<y>[-\w:]+)/(?P<z>[-\w:]+)/(?P<channels>[-\w,]+)/(?P<res>[-\w:]+)/$',
        views.zip_tiff_stacks, name='zip_tiff_stacks'),
    url(r'^sgram_from_ndviz/$', views.sgram_from_ndviz, name='sgram_from_ndviz'),
    url(r'^start_downsample/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/(?P<channel>[-\w]+)/$',
        views.start_downsample, name='start_downsample'),
    url(r'^stop_downsample/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/(?P<channel>[-\w]+)/$',
        views.stop_downsample, name='stop_downsample'),
    url(r'^channel_detail/(?P<coll>[-\w]+)/(?P<exp>[-\w]+)/(?P<channel>[-\w]+)/$',
        views.channel_detail, name='channel_detail'),
    url(r'^avatr_pull/$',
        views.avatr_pull, name='avatr_pull'),
    url(r'^avatr_push/$',
        views.avatr_push, name='avatr_push'),
]

synaptogram/models.py
from django.db import models

# Create your models here.

synaptogram/forms.py
from django import forms
from django.core import validators


class CutoutForm(forms.Form):
    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('channels')
        limits = kwargs.pop('limits')
        res_vals = kwargs.pop('res_vals')

        super(CutoutForm, self).__init__(*args, **kwargs)
        self.fields['channels'] = forms.MultipleChoiceField(
            label='Channels:', choices=[(c, c) for c in choices],
            widget=forms.CheckboxSelectMultiple,
            initial=[c for c in choices])
        # self.fields['channels'] = forms.ChoiceField(label='Channels',
        #     choices=[(c, c) for c in CHOICES])

        self.fields['x_min'] = forms.IntegerField(
            label='x_min', min_value=limits['x_start'], max_value=limits['x_stop'], initial=limits['x_start'])
        self.fields['x_max'] = forms.IntegerField(
            label='x_max', min_value=limits['x_start'], max_value=limits['x_stop'], initial=limits['x_stop'])

        self.fields['y_min'] = forms.IntegerField(
            label='y_min', min_value=limits['y_start'], max_value=limits['y_stop'], initial=limits['y_start'])
        self.fields['y_max'] = forms.IntegerField(
            label='y_max', min_value=limits['y_start'], max_value=limits['y_stop'], initial=limits['y_stop'])

        self.fields['z_min'] = forms.IntegerField(
            label='z_min', min_value=limits['z_start'], max_value=limits['z_stop'], initial=0)
        self.fields['z_max'] = forms.IntegerField(
            label='z_max', min_value=limits['z_start'], max_value=limits['z_stop'], initial=limits['z_stop'])

        self.fields['res_select'] = forms.ChoiceField(
            label='resolution:', choices=[(c, c) for c in res_vals], widget=forms.Select())

    next_action = (
        ('ndviz', 'Neurodata Viz links per slice'),
        ('tiff_stack', 'Download TIFF stack per channel'),
        ('sgram', 'Synaptogram'),
    )
    endpoint = forms.ChoiceField(label='Return:', choices=next_action,
                                 widget=forms.RadioSelect())


# add validations -
#   x_min < x_max

class AvatrPullForm(forms.Form):
    def __init__(self, *args, **kwargs):
        limits = kwargs.pop('limits')
        res_vals = kwargs.pop('res_vals')

        super(AvatrPullForm, self).__init__(*args, **kwargs)
        self.fields['x_min'] = forms.IntegerField(
            label='x_min', min_value=limits['x_start'], max_value=limits['x_stop'], initial=limits['x_start'])
        self.fields['x_max'] = forms.IntegerField(
            label='x_max', min_value=limits['x_start'], max_value=limits['x_stop'], initial=limits['x_stop'])

        self.fields['y_min'] = forms.IntegerField(
            label='y_min', min_value=limits['y_start'], max_value=limits['y_stop'], initial=limits['y_start'])
        self.fields['y_max'] = forms.IntegerField(
            label='y_max', min_value=limits['y_start'], max_value=limits['y_stop'], initial=limits['y_stop'])

        self.fields['z_min'] = forms.IntegerField(
            label='z_min', min_value=limits['z_start'], max_value=limits['z_stop'], initial=0)
        self.fields['z_max'] = forms.IntegerField(
            label='z_max', min_value=limits['z_start'], max_value=limits['z_stop'], initial=limits['z_stop'])

        self.fields['res_select'] = forms.ChoiceField(
            label='resolution:', choices=[(c, c) for c in res_vals], widget=forms.Select())

class AvatrPushForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(AvatrPushForm, self).__init__(*args, **kwargs)
        self.fields['file'] = forms.FileField(label='annotated_tiff')
        self.fields['file2'] = forms.FileField(label='metadata.cfg')

synaptogram/views.py
import os
import re
import time
import zipfile
from io import BytesIO
from io import StringIO


import blosc
import matplotlib
import numpy as np
import requests
import tifffile as tiff
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.contrib.auth import user_logged_in
from django.dispatch import receiver

matplotlib.use('Agg')
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

from .boss_remote import BossRemote
from .block_compute import block_compute
from .forms import CutoutForm, AvatrPullForm, AvatrPushForm

import sys
sys.path.append('synaptogram/')
from NDResource import NeuroDataResource
from block_compute import block_compute
import configparser

from intern.remote.boss import BossRemote as BR
from intern.resource.boss.resource import ChannelResource as CR#could do this manually

# All the actual views:


def index(request):
    request.session['next'] = 'synaptogram:coll_list'
    return render(request, 'synaptogram/index.html')


@receiver(user_logged_in)
def start_login_events(sender, user, request, **kwargs):
    setup_boss_remote(request)
    set_sess_exp(request)


def setup_boss_remote(request):
    # this is called when the user logs in and creates a boss remote class for the given user
    if 'boss_remote' not in request.session:
        request.session['boss_remote'] = BossRemote(request)


def set_sess_exp(request):
    # we set the session expiration to match the bearer token expiration
    id_token = request.session.get('id_token')
    if id_token is not None:  # if admin interfact we aren't using KeyCloak
        epoch_time_KC = id_token['exp']
        epoch_time_loc = round(time.time())  # + time.timezone
        new_exp_time = epoch_time_KC - epoch_time_loc
        request.session.set_expiry(new_exp_time)

def avatr_pull(request, coll, exp, ch, x, y, z, res):
    boss_remote = request.session['boss_remote']
    ch_info = boss_remote.get_ch_info(coll, exp, ch)
    dtype = ch_info['datatype']

    fname = 'media/' + '__'.join((coll, exp, ch)) + '.zip'

    with zipfile.ZipFile(fname, mode='x', allowZip64=True) as myzip:
        img_data, cut_url = get_chan_img_data(request, coll, exp, ch, x, y, z, res)
        #if img_data == 'authentication failure' or img_data == 'incorrect cutout arguments':
        #    raise Exception
        fn = 'media/{}__{}__{}.tiff'.format(
            coll, exp, ch).replace(':', '_')
        tiff.imsave(fn, img_data)
        myzip.write(fn, arcname='image.tiff')

        config = configparser.ConfigParser()
        config['METADATA'] = {'collection': coll,
                             'experiment': exp,
                             'channel': ch,
                             'x': x,
                             'y': y,
                             'z': z,
                             'resolution': res,
                             'dtype': dtype
                             }
        with open('media/metadata.cfg', 'w') as configfile:
            config.write(configfile)
        myzip.write('media/metadata.cfg', arcname='metadata.cfg')

    response = FileResponse(open(fname, 'rb'))
    response['Content-Disposition'] = 'attachment; filename="' + \
        fname.strip('media/') + '"'

    try:
        os.remove(fname)
        os.remove('media/metadata.cfg')
        os.remove(fn)
    except OSError:
        print('not removed')
        pass

    print(cut_url)
    return response

def avatr_push(request, file_img, file_meta, channel):
    boss_remote = request.session['boss_remote']
    rmt = BR('./synaptogram/neurodata.cfg')
    #get metadata
    meta = file_meta.read().decode('utf-8')
    param_list = meta.split('\n')
    params = {param.split(' = ')[0]:param.split(' = ')[1] for param in param_list[1:-2]}
    #unpack
    coll = params['collection']
    ch = params['channel']
    exp = params['experiment']
    x_rng = [int(i) for i in params['x'].split(':')]
    y_rng = [int(i) for i in params['y'].split(':')]
    z_rng = [int(i) for i in params['z'].split(':')]
    res = params['resolution']
    old_dtype = params['dtype']

    #chan_setup = ChannelResource(ch, coll, exp, 'annotation', datatype='uint64')
    #get image data
    img = tiff.imread(file_img).astype(np.uint64)
    #boss_remote.post(push_url, data=img,)
    #return(params)
    #return 'hi'
    ranges = block_compute(*x_rng,*y_rng,*z_rng)
    #chan = boss_remote.get_project(chan_setup)#NANI!o

    # Create a new channel
    chan_setup = CR(ch, coll, exp, 'annotation', datatype='uint64')
    chan = rmt.get_project(chan_setup)

    for some_range in ranges:
        x,y,z = some_range
        dx = [int(i-x_rng[0]) for i in x]
        dy = [int(i-y_rng[0]) for i in y]
        dz = [int(i-z_rng[0]) for i in z]
        img_vol = img[dz[0]:dz[1], dy[0]:dy[1], dx[0]:dx[1]]
        #rmt.create_cutout(chan, 0, x, y, z, np.ascontiguousarray(img_vol))#403 PERMISSIONS ERROR
        some_url = 'cutout/{}/{}/{}/{}/{}:{}/{}:{}/{}:{}'.format(coll,exp,channel,res,x[0],x[1],y[0],y[1],z[0],z[1])
        boss_remote.post_annotation(some_url, blosc.compress(np.ascontiguousarray(img_vol)))
    return

@login_required
def coll_list(request):
    collections = request.session['boss_remote'].get_collections()

    context = {'collections': collections}
    return render(request, 'synaptogram/coll_list.html', context)


@login_required
def exp_list(request, coll):
    experiments = request.session['boss_remote'].get_experiments(coll)
    if experiments is None:
        messages.error(
            request, 'No experiments found for collection: {}'.format(coll))
        return redirect(reverse('synaptogram:coll_list'))

    context = {'coll': coll, 'experiments': experiments}
    return render(request, 'synaptogram/exp_list.html', context)


@login_required
def cutout(request, coll, exp):
    boss_remote = request.session['boss_remote']
    # we need the channels to fill the form
    channels = boss_remote.get_channels(coll, exp)
    if channels is None:
        messages.error(
            request, 'No channels found for experiment: {}'.format(exp))
        return redirect(reverse('synaptogram:exp_list', args={coll}))

    exp_info = boss_remote.get_exp_info(coll, exp)
    res_vals = list(range(exp_info['num_hierarchy_levels']))

    # getting the coordinate frame limits for the experiment:
    coord_frame = boss_remote.get_coordinate_frame(coll, exp, exp_info)
    # important stuff out of coord_frame:
    # "x_start": 0,
    # "x_stop": 1000,
    # "y_start": 0,
    # "y_stop": 1000,
    # "z_start": 0,
    # "z_stop": 500

    # actual metadata in the BOSS for the experiment
    exp_meta_keyvals = boss_remote.get_exp_metadata(coll, exp)

    # merge the coord_frame data and some experiment metadata together
    exp_data = coord_frame
    copy_keys = ['creator', 'description', 'hierarchy_method',
                 'num_hierarchy_levels', 'num_time_samples',
                 'time_step', 'time_step_unit']
    exp_data.update({key: exp_info[key] for key in copy_keys})
    exp_data.update(exp_meta_keyvals)

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:

        form = CutoutForm(request.POST, channels=channels,
                          limits=coord_frame, res_vals=res_vals)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            x = str(form.cleaned_data['x_min']) + \
                ':' + str(form.cleaned_data['x_max'])
            y = str(form.cleaned_data['y_min']) + \
                ':' + str(form.cleaned_data['y_max'])
            z = str(form.cleaned_data['z_min']) + \
                ':' + str(form.cleaned_data['z_max'])

            res = form.cleaned_data['res_select']

            channels = form.cleaned_data['channels']

            pass_params_d = {'coll': coll, 'exp': exp, 'x': x,
                             'y': y, 'z': z, 'channels': ','.join(channels), 'res': res}
            pass_params = '&'.join(['%s=%s' % (key, value)
                                    for (key, value) in pass_params_d.items()])
            params = '?' + pass_params

            # redirect to a new URL:
            end_path = form.cleaned_data['endpoint']
            if end_path == 'sgram':
                return HttpResponseRedirect(
                    reverse('synaptogram:sgram') + params)
            elif end_path == 'ndviz':
                return HttpResponseRedirect(
                    reverse('synaptogram:ndviz_url_list') + params)
            elif end_path == 'tiff_stack':
                return HttpResponseRedirect(
                    reverse('synaptogram:tiff_stack') + params)

    # if a GET (or any other method) we'll create a blank form
    else:
        q = request.GET
        x_param = q.get('x')
        if x_param is not None:
            x, y, z = xyz_from_params(q)
            x_rng, y_rng, z_rng = create_voxel_rng(x, y, z)
            form = CutoutForm(channels=channels,
                              initial={'x_min': str(x_rng[0]), 'y_min': str(y_rng[0]), 'z_min': str(z_rng[0]),
                                       'x_max': str(x_rng[1]), 'y_max': str(y_rng[1]), 'z_max': str(z_rng[1])},
                              limits=coord_frame, res_vals=res_vals)
        else:
            form = CutoutForm(channels=channels,
                              limits=coord_frame, res_vals=res_vals)

    context = {'form': form, 'coll': coll, 'exp': exp, 'channels': channels,
               'exp_data': sorted(exp_data.items())}

synaptogram/templates/synaptogram/avatr.html
{% block content %}
<div style="width: 100%; overflow: hidden; align:center">
    <div>
        <h3>Boss Annotator:</h3>
        <h5>Download Volume</h5>
        <form action="{% url 'synaptogram:channel_detail' coll exp channel %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <div class="fieldWrapper">
                        <td>{{ pull_form.x_min.label_tag }}</td>
                        <td>{{ pull_form.x_min }}</td>
                    </div>
                </tr>

                <tr>
                    <div class="fieldWrapper">
                        <td>{{ pull_form.x_max.label_tag }}</td>
                        <td>{{ pull_form.x_max }}</td>
                    </div>
                </tr>

                <tr>
                    <div class="fieldWrapper">
                        <td>{{ pull_form.y_min.label_tag }}</td>
                        <td>{{ pull_form.y_min }}</td>
                    </div>
                </tr>

                <tr>
                    <div class="fieldWrapper">
                        <td>{{ pull_form.y_max.label_tag }}</td>
                        <td>{{ pull_form.y_max }}</td>
                    </div>
                </tr>

                <tr>
                    <div class="fieldWrapper">
                        <td>{{ pull_form.z_min.label_tag }}</td>
                        <td>{{ pull_form.z_min }}</td>
                    </div>
                </tr>

                <tr>
                    <div class="fieldWrapper">
                        <!--{{ form.z_max.errors }}-->
                        <td>{{ pull_form.z_max.label_tag }}</td>
                        <td>{{ pull_form.z_max }}</td>
                    </div>
                </tr>

                <tr>
                    <div class="fieldWrapper">
                        <td>{{ pull_form.res_select.label_tag }}</td>
                        <td>{{ pull_form.res_select }}</td>
                    </div>
                </tr>
            </table>
            <input type='submit' value='Submit' />
        </form>

    </div>

    <div style="margin-top: 100px;">
        <!--hr-->
        <!--h3>AVATR Push</h3-->
        <h5>Upload Annotated Volume</h5>
        <form enctype="multipart/form-data" action="{% url 'synaptogram:channel_detail' coll exp channel %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <div class="fieldWrapper">
                        <td>{{ push_form.file.label_tag }}</td>
                        <td>{{ push_form.file }}</td>
                    </div>
                </tr>
                <tr>
                    <div class="fieldWrapper">
                        <td>{{ push_form.file2.label_tag }}</td>
                        <td>{{ push_form.file2 }}</td>
                    </div>
                </tr>
            </table>
            <input type='submit' value='Submit' />
        </form>

    </div>
</div>
{% endblock %}

synaptogram/templates/synaptogram/back_to_form.html
<p> 
↑
<a href="{% url 'synaptogram:coll_list' %}">
    Collections</a>
| 
<a href="{% url 'synaptogram:exp_list' coll %}">
    Experiments</a>
| 
<a href="{% url 'synaptogram:cutout' coll exp %}">
    Channels</a>
</p>

synaptogram/templates/synaptogram/channel_detail.html
{% extends 'synaptogram/base.html' %}
{% block content %}
<div style='float:left'>
<p>
    ↑
    <a href="{% url 'synaptogram:coll_list' %}">
        Collections</a>
    |
    <a href="{% url 'synaptogram:exp_list' coll %}">
        Experiments</a>
    |
    <a href="{% url 'synaptogram:cutout' coll exp %}">
        Channels</a>
</p>

<h3>Channel detail</h3>

{% include 'synaptogram/coll_link.html' %}
{% include 'synaptogram/exp_link.html' %}
{% include 'synaptogram/channel_link.html' %}

<p>
    <strong>Type:</strong>
    {{channel_props.type}}
</p>

<p>
    <strong>Datatype:</strong>
    {{channel_props.datatype}}
</p>

<p><strong>NDViz:</strong>
    <a href="{{ ndviz_url }}" target="_blank">link</a>
</p>


<p><strong>Downsample status:</strong>
    {{ channel_props.downsample_status }}
    {% if channel_props.downsample_status == 'NOT_DOWNSAMPLED' %}
        <button onclick="myFunction()">Downsample</button>

        <span id="downsample"></span>

        <script>
        function myFunction() {
            var txt;
            if (confirm("Downsampling a channel can take a long time. We do not recommend downsampling more than one channel at a time.") == true) {
                txt = "<a href=\"{% url 'synaptogram:start_downsample' coll exp channel %}\">Start Downsample Job</a>";
            } else {
                txt = "";
            }
            document.getElementById("downsample").innerHTML = txt;
        }
        </script>

    {% elif channel_props.downsample_status == 'IN_PROGRESS' %}
            <button onclick="myFunction()">Cancel downsample job</button>

            <span id="downsample"></span>

            <script>
            function myFunction() {
                var txt;
                if (confirm("Canceling a downsample job will reset it's status to NOT_DOWNSAMPLED. Downsampling will have to be restarted from the beginning.") == true) {
                    txt = "<a href=\"{% url 'synaptogram:stop_downsample' coll exp channel %}\">Stop Downsample Job</a>";
                } else {
                    txt = "";
                }
                document.getElementById("downsample").innerHTML = txt;
            }
            </script>
    {% endif %}
</p>

<p><strong>Permissions:</strong>
<ul>
    {% for p in permissions %}
        <li>
            <strong>Group:</strong> {{p.group}} (<a href="https://api.boss.neurodata.io/v1/mgmt/group/{{p.group}}" target="_blank">manage</a>)<br>
            <strong>Permissions:</strong>
            <ul>
            {% for p_g in p.permissions %}
                <li>{{p_g}}</li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>
</p>
</div>

<div class='exp_metadata' style='margin-top:15px; padding-left:20px; padding-right:20px'>
    {% include 'synaptogram/avatr.html' %}
</div>

{% endblock %}

synaptogram/templates/synaptogram/cutout.html
{% extends 'synaptogram/base.html' %}
{% block content %}


<script language="JavaScript">
    function toggle(source, checkboxes_name) {
        checkboxes = document.getElementsByName(checkboxes_name);
        for (var i = 0, n = checkboxes.length; i < n; i++) {
            checkboxes[i].checked = source.checked;
        }
    }
</script>

{% include 'synaptogram/coord_frame_detail.html' %}

<div class="page-title">
    <p>
        ↑
        <a href="{% url 'synaptogram:coll_list' %}">
            Collections</a>
        | 
        <a href="{% url 'synaptogram:exp_list' coll %}">
            Experiments</a>
    </p>
    
    <h3>Experiment Detail</h3>
</div>

<div class="exp_content">

{% include 'synaptogram/coll_link.html' %} 
{% include 'synaptogram/exp_link.html' %}

<p>
    <strong>Channels</strong>
            <a href="{% url 'synaptogram:ndviz_url' coll exp%}" target="_blank">NDViz</a>
            {% if channels|length > 3 %} (all but the first 3 disabled) {% endif %}
    <ul>
        {% for ch in channels %}
        <li>
            <a href="{% url 'synaptogram:channel_detail' coll exp ch %}">{{ch}}</a>
            (<a href="{% url 'synaptogram:ndviz_url' coll exp ch%}" target="_blank">NDViz</a>)
            (<a href="https://api.boss.neurodata.io/v1/mgmt/resources/{{coll}}/{{exp}}/{{ch}}" target="_blank">manage</a>)
        </li>
        {% endfor %}
    </ul>
</p>

<h4>Cutout:</h4>

<form action="{% url 'synaptogram:cutout' coll exp %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <div class="fieldWrapper">
                {{ form.x_min.errors }}
                <td>{{ form.x_min.label_tag }}

                </td>

                <td>{{ form.x_min }}</td>
            </div>
        </tr>

        <tr>
            <div class="fieldWrapper">
                {{ form.x_max.errors }}
                <td>{{ form.x_max.label_tag }}</td>
                <td>{{ form.x_max }}</td>
            </div>
        </tr>

        <tr>
            <div class="fieldWrapper">
                {{ form.y_min.errors }}
                <td>{{ form.y_min.label_tag }}</td>
                <td>{{ form.y_min }}</td>
            </div>
        </tr>

        <tr>
            <div class="fieldWrapper">
                {{ form.y_max.errors }}
                <td>{{ form.y_max.label_tag }}</td>
                <td>{{ form.y_max }}</td>
            </div>
        </tr>


        <tr>
            <div class="fieldWrapper">
                {{ form.z_min.errors }}
                <td>{{ form.z_min.label_tag }}</td>
                <td>{{ form.z_min }}</td>
            </div>
        </tr>

        <tr>
            <div class="fieldWrapper">
                {{ form.z_max.errors }}
                <td>{{ form.z_max.label_tag }}</td>
                <td>{{ form.z_max }}</td>
            </div>
        </tr>

        <tr>
            <div class="fieldWrapper">
                {{ form.channels.errors }}
                <td>{{ form.channels.label_tag }}</td>
                <td>
                    <label for="toggle_ch_checkbox">
                        <input type="checkbox" onClick="toggle(this, 'channels' )" 
                        id="toggle_ch_checkbox" checked/> 
                        Toggle channels
                    </label><br>
                    {{ form.channels }}
                </td>
            </div>
        </tr>

        <tr>
            <div class="fieldWrapper">
                {{ form.endpoint.errors }}
                <td>{{ form.endpoint.label_tag }}</td>
                <td>
                <ul id="id_endpoint">
                {% for radio in form.endpoint %}
                    <li>
                        {{ radio }}
                        {% if radio.choice_label == 'Download TIFF stack per channel' %}
                            at {{ form.res_select.label_tag }}
                            {{ form.res_select }}
                        {% endif %}
                    </li>
                {% endfor %}
                </ul>
                </td>
            </div>
        </tr>
    </table>
    <input type="submit" value="Submit" />
</form>

</div>
{% endblock %}

synaptogram/templates/synaptogram/exp_link.html
<p><strong>Experiment:</strong>
<!-- https://api.boss.neurodata.io/v1/mgmt/resources/collman/collman14v2 -->
<a href="{% url 'synaptogram:cutout' coll exp %}">{{ exp }}</a>
(<a href="https://api.boss.neurodata.io/v1/mgmt/resources/{{coll}}/{{exp}}" target="blank">manage</a>)
</p>

synaptogram/templates/synaptogram/exp_list.html
{% extends 'synaptogram/base.html' %} 
{% block content %}


<p>
    ↑
    <a href="{% url 'synaptogram:coll_list' %}">
        Collections</a>
</p>

<h3>Experiment list</h3>

{% include 'synaptogram/coll_link.html' %}

<ul>
    {% for exp in experiments %}
    <li>
        <a href="{% url 'synaptogram:cutout' coll exp %}">{{exp}}</a>
        (<a href="{% url 'synaptogram:ndviz_url' coll exp%}" target="_blank">NDViz</a>)
        (<a href="https://api.boss.neurodata.io/v1/mgmt/resources/{{coll}}/{{exp}}" target="_blank">manage</a>)
    </li>
    {% endfor %}
</ul>

{% endblock %}